version: "3"

#docker-compose for development environment
services:
  web:
    image: nginx
    container_name: web_new
    ports:
      - "8082:80"
      - "442:443"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/letsencrypt:/etc/letsencrypt

  app:
    build:
      context: .
      target: development-stage
      dockerfile: docker/Dockerfile
    container_name: app_new
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    container_name: db_new
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data_new:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma_new
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=db_new
      - PMA_PORT=3306
      - PMA_ARBITRARY=1

volumes:
  mysql_data_new:
